
# Generated by Django 4.0.1 on 2022-01-24 07:42


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYIT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('paymentslip', models.FileField(null=True, upload_to='paymentslip/')),
                ('status', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
