# Generated by Django 4.0.1 on 2022-01-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYIT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reedemed_refferal',
            field=models.IntegerField(default=0),
        ),
    ]
