# Generated by Django 3.2 on 2022-01-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYIT', '0002_alter_lelofamerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchaserequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
