# Generated by Django 3.2.4 on 2022-01-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYIT', '0002_alter_profile_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
