# Generated by Django 4.0.1 on 2022-01-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYIT', '0002_creditpurchaserequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lelofamerequest',
            old_name='request',
            new_name='plan',
        ),
    ]
