# Generated by Django 3.2 on 2022-01-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYIT', '0003_alter_creditpurchaserequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpurchaserequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lelofamerequest',
            name='id',
        ),
        migrations.AddField(
            model_name='creditpurchaserequest',
            name='txn',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lelofamerequest',
            name='txn',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
