# Generated by Django 4.0.1 on 2022-01-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYIT', '0003_rename_request_lelofamerequest_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lelofamerequest',
            old_name='userusername',
            new_name='userhandle',
        ),
    ]
