# Generated by Django 4.0.1 on 2022-01-25 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FYIT', '0004_rename_userusername_lelofamerequest_userhandle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeloFameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_spends', models.IntegerField()),
                ('platform', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('userhandle', models.CharField(max_length=200)),
                ('credit_left', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.CharField(max_length=300)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CreditLog',
        ),
    ]
