# Generated by Django 3.2 on 2022-01-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYIT', '0004_auto_20220131_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpurchaselog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lelofamelog',
            name='id',
        ),
        migrations.AddField(
            model_name='creditpurchaselog',
            name='txn',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lelofamelog',
            name='txn',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
