# Generated by Django 3.2 on 2022-01-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYIT', '0006_lelofamerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchaserequest',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
